### ISSUE TITLE
发送icon之后，界面上的icon和键盘上的icon不一致 会乱码

### ISSUE THREAD

**Issue by zuowutan** [OneGreenHand/Emoji#1]
如题 作者麻烦看一下，以下是测试信息 机型：中兴 系统：5.1

**Comment by OneGreenHand** [comment]
@zuowutan 显示为☐或者是空格吗

**Comment by OneGreenHand** [comment]
如果是当前设备支持的 Emoji，是可以正常显示。也可直接setText("\uD83D\uDE33")查看是否显示
，如果Emoji 无法显示，会被显示成一个豆腐块 “☐” ，可尝试使用官方的EmojiCompat 支持库

**Comment by OneGreenHand** [comment]
v1.2.版本已修复此问题，目前最新版本为v1.2.1
